Add RECURRENCE-ID with range parameter.
niccokunzmann/python-recurring-ical-events pull request #181
Opened 2024-09-18 10:26 UTC by jabiertxof

Add RECURRENCE-ID with range parameter.

Fix https://github.com/niccokunzmann/python-recurring-ical-events/issues/75

2024-09-18 12:53 UTC, jabiertxof commented
WIP: Need to include rrule

2024-09-18 13:23 UTC, jabiertxof commented
Added test for rdate

2024-09-18 17:16 UTC, niccokunzmann requested changes
Hi, I request changes but first of all! Cool! This looks really good! Let me know which changes you would like to tackle and which ones not so I can create a PR to your branch for those that you do not like ;)

Also, to close the issue we need more tests, I believe..

2024-09-18 17:16 UTC, niccokunzmann commented on test/conftest.py
> +sys.path.append(os.path.join(Path(__file__).resolve().parent, 'inc'))
I can send a refactoring for this but it is alright.
With Path() you do `Path(__file__) / 'inc'`

2024-09-19 19:29 UTC, jabiertxof commented on recurring_ical_events.py
> +    def thisandfuture(self) -> bool:
thanks

2024-09-19 19:29 UTC, jabiertxof commented on recurring_ical_events.py
> -    ATTRIBUTES_TO_DELETE_ON_COPY = ["RRULE", "RDATE", "EXDATE"]
fixed

2024-09-19 19:29 UTC, jabiertxof commented on recurring_ical_events.py
> +                self.recurrence.core = prev_adapter
fixed

2024-09-19 19:30 UTC, jabiertxof commented on recurring_ical_events.py
> +            if prev_adapter and adapter is self.recurrence.core:
thanks

2024-09-19 19:30 UTC, jabiertxof commented on test/conftest.py
> +print(os.path.join(Path(__file__).resolve().parent, 'inc'))
legacy code to test local removed

2024-09-19 22:17 UTC, jabiertxof commented on test/test_issue_75_range_parameter.py
> +# TODO: Test DTSTART and DTEND
done

2024-09-19 22:18 UTC, jabiertxof commented on recurring_ical_events.py
> +        prev_adapter = None
done

2024-09-19 22:18 UTC, jabiertxof commented on recurring_ical_events.py
> +                for start in rule.between(rule._dtstart, span_stop_dt, inc=True):
fixed

2024-09-26 10:24 UTC, niccokunzmann commented
Thanks for your additions! I will merge this and open another PR with the additional tests.. This does not yet solve the issue but it is really close.

2024-09-26 10:24 UTC, merged